spring:
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.marketplace.notificationservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
