spring:
  application:
    name: user-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:CeTN4JXsOedYNLB9vVSoFbN498s9ql1TftQR7p3qFoh}
  expiration: 86400000
