spring:
  application:
    name: product-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cache:
    type: redis
    redis:
      time-to-live: 600000

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: product-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.marketplace.orderservice.event.OrderEvent:com.marketplace.productservice.event.OrderEvent"

server:
  port: 8082

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:product-images}

spring.servlet.multipart:
  max-file-size: 5MB
  max-request-size: 5MB
