spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2000ms

logging:
  level:
    com.marketplace.productservice: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: never
